# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 22:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuentas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta_nombre', models.CharField(max_length=128)),
                ('cuenta_descripcion', models.TextField(blank=True, null=True)),
                ('cuenta_numero', models.IntegerField()),
                ('depreciacion_nombre', models.CharField(blank=True, max_length=128, null=True)),
                ('depreciacion_descripcion', models.TextField(blank=True, null=True)),
                ('depreciacion_numero', models.IntegerField(blank=True, null=True)),
                ('depreciacion_porcentaje', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.CharField(blank=True, max_length=64, null=True)),
                ('workstation_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Cuentas',
                'managed': True,
            },
        ),
    ]
