# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 22:57
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacontable',
            name='create_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 28, 22, 57, 43, 322000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='update_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 28, 22, 57, 45, 234000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='workstation_ip',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='workstation_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
