# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 05:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Contabilidad', '0002_auto_20160228_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaDepreciacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('numero_cuenta', models.IntegerField()),
                ('porcentaje', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.CharField(blank=True, max_length=64, null=True)),
                ('workstation_ip', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'CuentaDepreciacion',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='cuentacontable',
            name='cuenta_depreciacion',
        ),
        migrations.RemoveField(
            model_name='cuentacontable',
            name='depreciacion',
        ),
        migrations.AddField(
            model_name='cuentadepreciacion',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contabilidad.CuentaContable'),
        ),
        migrations.AddField(
            model_name='cuentadepreciacion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
