# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilidad', '0002_cuentas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas',
            name='depreciacion_nombre',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cuentas',
            name='depreciacion_numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuentas',
            name='depreciacion_porcentaje',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
