# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-18 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilidad', '0003_auto_20160411_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentacontable',
            name='depreciacion',
        ),
        migrations.RemoveField(
            model_name='cuentacontable',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cuentadepreciacion',
            name='user',
        ),
        migrations.DeleteModel(
            name='CuentaContable',
        ),
        migrations.DeleteModel(
            name='CuentaDepreciacion',
        ),
    ]
