# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 22:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RecursosHumanos', '0001_initial'),
        ('Institucion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('razon_social', models.CharField(max_length=128)),
                ('direccion_fiscal', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('ruc', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.CharField(blank=True, max_length=64, null=True)),
                ('workstation_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('duenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Persona', to='RecursosHumanos.Persona')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institucion.Institucion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Proveedor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProveedorTelefonos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16)),
                ('operador', models.CharField(choices=[(1, b'Claro'), (2, b'Movistar'), (3, b'Bitel'), (4, b'Entel'), (5, b'Fijo')], default=5, max_length=1)),
                ('descriptor', models.CharField(blank=True, max_length=32, null=True)),
                ('create_at', models.DateTimeField(auto_now=True, null=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institucion.Institucion')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proveedor.Proveedor')),
            ],
            options={
                'db_table': 'ProveedorTelefonos',
                'managed': True,
            },
        ),
    ]
