# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='direccion_fiscal',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='proveedortelefonos',
            name='operador',
            field=models.CharField(choices=[(1, b'Claro'), (2, b'Movistar'), (3, b'Bitel'), (4, b'Entel'), (5, b'Fijo')], default=5, max_length=1),
        ),
    ]
