# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='duenio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Persona', to='RecursosHumanos.Persona'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ruc',
            field=models.IntegerField(max_length=15),
        ),
    ]
