# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-11 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='duenio',
            new_name='persona',
        ),
    ]
