# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-12 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0002_auto_20161011_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona', to='RecursosHumanos.Persona'),
        ),
    ]
