# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 13:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0002_auto_20160328_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='duenio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duenio', to=settings.AUTH_USER_MODEL),
        ),
    ]
