# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0002_auto_20160415_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='ruc',
            field=models.IntegerField(),
        ),
    ]
