# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 22:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Institucion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('modulos', models.CharField(blank=True, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.CharField(blank=True, max_length=64, null=True)),
                ('workstation_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institucion.Institucion')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Institucion.Local')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Institucion.Sede')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Area',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=32, null=True)),
                ('apellido_paterno', models.CharField(max_length=64)),
                ('apellido_materno', models.CharField(max_length=64)),
                ('nombres', models.CharField(max_length=64)),
                ('tipo_documento', models.CharField(blank=True, choices=[(b'D', b'DNI')], default=b'D', max_length=1, null=True)),
                ('nro_documento', models.CharField(max_length=16)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('ubigeo', models.CharField(blank=True, max_length=6, null=True)),
                ('direccion', models.CharField(blank=True, max_length=128, null=True)),
                ('referencia_direccion', models.TextField(blank=True, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=1, null=True)),
                ('genero', models.CharField(blank=True, choices=[(b'M', b'Masculino'), (b'F', b'Femenino')], default=b'M', max_length=1, null=True)),
                ('grado_academico', models.CharField(blank=True, max_length=1, null=True)),
                ('imagen', models.CharField(blank=True, max_length=256, null=True)),
                ('img_documento', models.CharField(blank=True, max_length=256, null=True)),
                ('tipo', models.CharField(blank=True, max_length=1, null=True)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.CharField(blank=True, max_length=64, null=True)),
                ('workstation_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institucion.Institucion')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Institucion.Local')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Institucion.Sede')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Persona',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PersonaTelefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16)),
                ('operador', models.CharField(max_length=1)),
                ('descriptor', models.CharField(blank=True, max_length=32, null=True)),
                ('create_at', models.DateTimeField(auto_now=True, null=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institucion.Institucion')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institucion.Local')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecursosHumanos.Persona')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institucion.Sede')),
            ],
            options={
                'db_table': 'PersonaTelefono',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('all_sedes', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.CharField(blank=True, max_length=64, null=True)),
                ('workstation_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecursosHumanos.Area')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institucion.Institucion')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Institucion.Local')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Institucion.Sede')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Puesto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_aportantes', models.IntegerField(blank=True, null=True)),
                ('nro_dependientes', models.IntegerField(blank=True, null=True)),
                ('ingreso_familiar', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('vivienda_tipo', models.CharField(blank=True, max_length=64, null=True)),
                ('vivienda_nro_habitantes', models.IntegerField(blank=True, null=True)),
                ('vivienda_servicio', models.CharField(blank=True, max_length=256, null=True)),
                ('vivienda_situacion', models.CharField(blank=True, max_length=64, null=True)),
                ('vivienda_material', models.CharField(blank=True, max_length=64, null=True)),
                ('enfermedades', models.CharField(blank=True, max_length=256, null=True)),
                ('enfermedad_cronica', models.CharField(blank=True, max_length=256, null=True)),
                ('discapacidad', models.CharField(blank=True, max_length=256, null=True)),
                ('alergia', models.CharField(blank=True, max_length=256, null=True)),
                ('objetivo_personal', models.TextField(blank=True, null=True)),
                ('tipo_contrato', models.CharField(blank=True, max_length=128, null=True)),
                ('tipo', models.CharField(blank=True, max_length=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.CharField(blank=True, max_length=64, null=True)),
                ('workstation_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institucion.Ambiente')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institucion.Institucion')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institucion.Local')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecursosHumanos.Persona')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institucion.Sede')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Trabajador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TrabajadorPuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.CharField(blank=True, max_length=64, null=True)),
                ('workstation_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institucion.Institucion')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institucion.Local')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecursosHumanos.Puesto')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institucion.Sede')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecursosHumanos.Trabajador')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TrabajadorPuesto',
                'managed': True,
            },
        ),
    ]
