# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecursosHumanos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='codigo',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
