# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 04:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0003_auto_20160404_0007'),
        ('RecursosHumanos', '0002_trabajador_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajadorpuesto',
            name='ambiente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Institucion.Ambiente'),
            preserve_default=False,
        ),
    ]
