# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecursosHumanos', '0002_auto_20160328_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Institucion.Local'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Institucion.Sede'),
        ),
    ]
