# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecursosHumanos', '0003_trabajadorpuesto_ambiente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajadorpuesto',
            name='ambiente',
        ),
        migrations.RemoveField(
            model_name='trabajadorpuesto',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='trabajadorpuesto',
            name='local',
        ),
        migrations.RemoveField(
            model_name='trabajadorpuesto',
            name='puesto',
        ),
        migrations.RemoveField(
            model_name='trabajadorpuesto',
            name='sede',
        ),
        migrations.RemoveField(
            model_name='trabajadorpuesto',
            name='trabajador',
        ),
        migrations.RemoveField(
            model_name='trabajadorpuesto',
            name='user',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RecursosHumanos.Puesto'),
        ),
        migrations.DeleteModel(
            name='TrabajadorPuesto',
        ),
    ]
