# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecursosHumanos', '0004_auto_20160414_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='personatelefono',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='personatelefono',
            name='update_at',
            field=models.DateTimeField(auto_now=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='puesto',
            name='all_sedes',
            field=models.NullBooleanField(),
        ),
    ]
