# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecursosHumanos', '0007_puesto_all_sedes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puesto',
            name='all_sedes',
        ),
    ]
