# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecursosHumanos', '0008_remove_puesto_all_sedes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nro_documento',
            field=models.IntegerField(max_length=16),
        ),
    ]
