# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
