# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='tipo_ambiente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Institucion.TipoAmbiente'),
            preserve_default=False,
        ),
    ]
