# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='direccion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
