# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 06:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Institucion', '0002_auto_20160121_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=64)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.CharField(blank=True, max_length=64, null=True)),
                ('workstation_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Colaborador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='institucion',
            options={},
        ),
        migrations.AddField(
            model_name='institucion',
            name='slug',
            field=models.SlugField(default='insti', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='institucion',
            table=None,
        ),
        migrations.AddField(
            model_name='puesto',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Institucion', to='Institucion.Institucion'),
        ),
        migrations.AddField(
            model_name='puesto',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Use', to=settings.AUTH_USER_MODEL),
        ),
    ]
