# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0003_auto_20160201_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='slug',
            field=models.SlugField(max_length=16, unique=True),
        ),
    ]
