# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0004_auto_20160217_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
