# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 22:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proveedor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RecursosHumanos', '0001_initial'),
        ('CatalogoBienes', '0001_initial'),
        ('Institucion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoFijo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=6)),
                ('adquisiciones_adicionales', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('mejoras', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('retiros', models.CharField(blank=True, max_length=50, null=True)),
                ('otros_ajustes', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_revaluado', models.CharField(blank=True, max_length=150, null=True)),
                ('efectuada', models.CharField(blank=True, max_length=150, null=True)),
                ('valor_ajustado_2014', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_adquisicion', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('tipo_depreciacion_metodo', models.CharField(max_length=200)),
                ('tipo_depreciacion_nro_doc', models.CharField(max_length=200)),
                ('porcentaje_depreciacion', models.IntegerField()),
                ('depreciacion_acumulada_cierre_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('valor_depre_ejercicio_sin_revaluacion', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('valor_depre_relacionada_bajas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('valor_depre_relacionada_otros', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('depreciacion_acumulada_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('valor_neto', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('valor_depreciacion_de_revaluacion', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.CharField(blank=True, max_length=64, null=True)),
                ('workstation_ip', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'ActivoFijo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BajaBien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(blank=True, max_length=100, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.CharField(blank=True, max_length=64, null=True)),
                ('workstation_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('ambiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Institucion.Ambiente')),
            ],
            options={
                'db_table': 'BajaBien',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=200, null=True)),
                ('modelo', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=200, null=True)),
                ('dimension', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('otro_detalle', models.TextField(blank=True, null=True)),
                ('saldo_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('estado', models.CharField(choices=[(1, b'Bueno'), (2, b'Regular'), (3, b'De baja')], max_length=1)),
                ('fecha_revaluacion', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.CharField(blank=True, max_length=64, null=True)),
                ('workstation_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('ambiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Institucion.Ambiente')),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatalogoBienes.CatalogoBien')),
            ],
            options={
                'db_table': 'Bien',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleIngreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('pendiente', models.BooleanField(default=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.CharField(blank=True, max_length=64, null=True)),
                ('workstation_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatalogoBienes.CatalogoBien')),
            ],
            options={
                'db_table': 'DetalleIngreso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DisposicionBien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('descripcion', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.CharField(blank=True, max_length=64, null=True)),
                ('workstation_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institucion.Ambiente')),
            ],
            options={
                'db_table': 'DisposicionBien',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DisposicionBienDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.CharField(blank=True, max_length=64, null=True)),
                ('workstation_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('detalle_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bienes.DetalleIngreso')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DisposicionBienDetalle',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_compra', models.CharField(blank=True, max_length=24, null=True)),
                ('guia_remision', models.CharField(max_length=24, unique=True)),
                ('tipo_comprobante', models.CharField(blank=True, choices=[(1, b'Factura'), (2, b'Boleta')], max_length=1, null=True)),
                ('numero_comprobante', models.CharField(blank=True, max_length=24, null=True)),
                ('nombre', models.CharField(blank=True, max_length=24, null=True)),
                ('condicion', models.CharField(blank=True, choices=[(1, b'Compra'), (2, b'Donaci\xc3\xb3n'), (3, b'Bonificaci\xc3\xb3n')], max_length=1, null=True)),
                ('tipo_moneda', models.CharField(blank=True, choices=[(1, b'Soles'), (2, b'Dolares')], max_length=1, null=True)),
                ('tipo_cambio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pendiente', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.CharField(blank=True, max_length=64, null=True)),
                ('workstation_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedor', to='Proveedor.Proveedor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Ingreso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoAlmacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TipoAlmacen',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TrasladoBien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.CharField(blank=True, max_length=64, null=True)),
                ('workstation_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bienes.Bien')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institucion.Ambiente')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='Institucion.Ambiente')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitante', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TrasladoBien',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='disposicionbien',
            name='detalle_disposicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bienes.DisposicionBienDetalle'),
        ),
        migrations.AddField(
            model_name='disposicionbien',
            name='guia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bienes.Ingreso'),
        ),
        migrations.AddField(
            model_name='disposicionbien',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institucion.Local'),
        ),
        migrations.AddField(
            model_name='disposicionbien',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institucion.Sede'),
        ),
        migrations.AddField(
            model_name='disposicionbien',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecursosHumanos.Trabajador'),
        ),
        migrations.AddField(
            model_name='disposicionbien',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleingreso',
            name='ingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bienes.Ingreso'),
        ),
        migrations.AddField(
            model_name='detalleingreso',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bien',
            name='detalle_ingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bienes.DetalleIngreso'),
        ),
        migrations.AddField(
            model_name='bien',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Institucion.Local'),
        ),
        migrations.AddField(
            model_name='bien',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bien',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RecursosHumanos.Trabajador'),
        ),
        migrations.AddField(
            model_name='bajabien',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bienes.Bien'),
        ),
        migrations.AddField(
            model_name='bajabien',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bienes.Bien'),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
