# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bienes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingreso',
            old_name='numero_factura',
            new_name='numero_comprobante',
        ),
        migrations.AddField(
            model_name='ingreso',
            name='tipo_comprobante',
            field=models.CharField(blank=True, choices=[(1, b'Factura'), (2, b'Boleta')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='condicion',
            field=models.CharField(blank=True, choices=[(1, b'Compra'), (2, b'Donaci\xc3\xb3n'), (3, b'Bonificaci\xc3\xb3n')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='guia_remision',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='nombre',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='orden_compra',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
