# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 13:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0003_auto_20160328_0827'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CatalogoBienes', '0003_auto_20160228_1757'),
        ('Bienes', '0002_auto_20160228_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleIngreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tipo_moneda', models.CharField(choices=[(1, b'Sol'), (2, b'Dolar')], max_length=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.CharField(blank=True, max_length=64, null=True)),
                ('workstation_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatalogoBienes.CatalogoBien')),
                ('tipo_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bienes.TipoMedida')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DetalleIngreso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guia_remision', models.CharField(max_length=24)),
                ('nombre', models.CharField(max_length=24)),
                ('condicion', models.CharField(choices=[(1, b'Compra'), (2, b'Donaci\xc3\xb3n')], max_length=1)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.CharField(blank=True, max_length=64, null=True)),
                ('workstation_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proveedor.Proveedor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Ingreso',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='almacen',
            name='catalogo_de_bien',
        ),
        migrations.RemoveField(
            model_name='almacen',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='almacen',
            name='tipo_almacen',
        ),
        migrations.RemoveField(
            model_name='almacen',
            name='tipo_medida',
        ),
        migrations.RemoveField(
            model_name='almacen',
            name='user',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='catalogo_de_bien',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='user',
        ),
        migrations.RemoveField(
            model_name='altabien',
            name='inventario',
        ),
        migrations.RemoveField(
            model_name='asignacionbien',
            name='inventario',
        ),
        migrations.RemoveField(
            model_name='disposicionbien',
            name='inventario',
        ),
        migrations.RemoveField(
            model_name='trasladobien',
            name='inventario',
        ),
        migrations.DeleteModel(
            name='Almacen',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
