# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bienes', '0002_auto_20160416_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
