# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bienes', '0003_auto_20160328_0827'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detalleingreso',
            table='DetalleIngreso',
        ),
    ]
