# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-30 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bienes', '0003_bien_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='estado',
            field=models.CharField(blank=True, choices=[(1, b'Bueno'), (2, b'Regular'), (3, b'De baja')], max_length=1, null=True),
        ),
    ]
