# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bienes', '0003_ingreso_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='tipo_cambio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='tipo_moneda',
            field=models.CharField(blank=True, choices=[(1, b'Soles'), (2, b'Dolares')], max_length=1, null=True),
        ),
    ]
