# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bienes', '0004_auto_20160416_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleingreso',
            name='pendiente',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='pendiente',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='ambiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Institucion.Ambiente'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='estado',
            field=models.CharField(choices=[(1, b'Bueno'), (2, b'Regular'), (3, b'De baja')], max_length=1),
        ),
        migrations.AlterField(
            model_name='bien',
            name='fecha_revaluacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Institucion.Local'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='saldo_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RecursosHumanos.Trabajador'),
        ),
    ]
