# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bienes', '0005_auto_20160417_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='guia_remision',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
    ]
