# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bienes', '0005_bien_almacen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposicionbien',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
