# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bienes', '0006_auto_20160417_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleingreso',
            name='tipo_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bienes.TipoMedida'),
        ),
    ]
