# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-02 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bienes', '0006_auto_20160502_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='fecha_activa',
            field=models.DateField(blank=True, null=True),
        ),
    ]
