# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bienes', '0007_auto_20160417_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='guia_remision',
            field=models.CharField(default=1, max_length=24, unique=True),
            preserve_default=False,
        ),
    ]
