# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bienes', '0008_auto_20160417_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleingreso',
            name='pendiente',
        ),
        migrations.RemoveField(
            model_name='detalleingreso',
            name='tipo_medida',
        ),
        migrations.DeleteModel(
            name='TipoMedida',
        ),
    ]
