# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-18 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bienes', '0009_auto_20160417_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleingreso',
            name='tipo_moneda',
        ),
        migrations.AddField(
            model_name='bien',
            name='detalle_ingreso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Bienes.DetalleIngreso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bien',
            name='codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedor', to='Proveedor.Proveedor'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
