# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-18 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bienes', '0010_auto_20160417_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleingreso',
            name='pendiente',
            field=models.CharField(choices=[(1, b'Sol'), (2, b'Dolar')], default=True, max_length=1),
            preserve_default=False,
        ),
    ]
