# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-18 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bienes', '0011_detalleingreso_pendiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleingreso',
            name='pendiente',
            field=models.BooleanField(default=True),
        ),
    ]
