# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 22:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Contabilidad', '0001_initial'),
        ('Institucion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoBien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.CharField(blank=True, max_length=64, null=True)),
                ('workstation_ip', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'CatalogoBien',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.CharField(blank=True, max_length=64, null=True)),
                ('workstation_ip', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'Clase',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.CharField(blank=True, max_length=64, null=True)),
                ('workstation_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institucion.Institucion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Grupo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoCatalogoBien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('workstation_name', models.CharField(blank=True, max_length=64, null=True)),
                ('workstation_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institucion.Institucion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TipoCatalogoBien',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='clase',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatalogoBienes.Grupo'),
        ),
        migrations.AddField(
            model_name='clase',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institucion.Institucion'),
        ),
        migrations.AddField(
            model_name='clase',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catalogobien',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatalogoBienes.Clase'),
        ),
        migrations.AddField(
            model_name='catalogobien',
            name='cuenta_contable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contabilidad.Cuentas'),
        ),
        migrations.AddField(
            model_name='catalogobien',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institucion.Institucion'),
        ),
        migrations.AddField(
            model_name='catalogobien',
            name='tipo_catalogo_bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatalogoBienes.TipoCatalogoBien'),
        ),
        migrations.AddField(
            model_name='catalogobien',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
