# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-18 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatalogoBienes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogobien',
            name='cuenta_contable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contabilidad.Cuentas'),
        ),
    ]
